OF\ContractsBundle\Entity\Contract:
    type: entity
    table: null
    repositoryClass: OF\ContractsBundle\Repository\ContractRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        bounty:
            type: smallint
            nullable: true
        difficulty:
            type: string
            length: 255
        report:
            type: string
            length: 255
    lifecycleCallbacks: {  }
