of_contracts_homepage:
    path:     /
    defaults: { _controller: OFContractsBundle:Default:index }
of_contracts_new_contract:
    path:   newcontract/
    defaults: { _controller: OFContractsBundle:Enterprise:newContract }